updates regarding the script?

diff --git a/ore b/ore
--- a/ore
+++ b/ore
@@ -1,11 +1,21 @@
 #!/bin/sh
+#  ::: :::::::: :::   :::    ::: ::::::::::: ::::::::   ::::::::  ::: ::::::::           :::     :::    :::   ::: :::::::::  :::        :::    ::: :::::::::: :::        :::::::::  :::::::::: :::::::::        :::::::          :::::::::     :::      ::::::::  ::::    ::::      :::     ::::    :::      :::       ::: :::::::::      :::     :::::::::  :::::::::    ::: :::::::::: :::   :::::::::  
+# :+: :+:    :+: :+:  :+:    :+:     :+:    :+:    :+: :+:    :+: :+ :+:    :+:        :+: :+:   :+:    :+:  :+:  :+:    :+:  :+:       :+:    :+: :+:        :+:        :+:    :+: :+:        :+:    :+:      :+:   :+:         :+:    :+:  :+: :+:   :+:    :+: +:+:+: :+:+:+   :+: :+:   :+:+:   :+:      :+:       :+: :+:    :+:   :+: :+:   :+:    :+: :+:    :+:  :+:  :+:         :+:  :+:    :+: 
+#+:+  +:+    +:+  +:+ +:+    +:+     +:+    +:+    +:+       +:+     +:+              +:+   +:+  +:+    +:+ +:+   +:+    +:+   +:+      +:+    +:+ +:+        +:+        +:+    +:+ +:+        +:+    +:+       +:+ +:+          +:+    +:+ +:+   +:+  +:+        +:+ +:+:+ +:+  +:+   +:+  :+:+:+  +:+      +:+       +:+ +:+    +:+  +:+   +:+  +:+    +:+ +:+    +:+ +:+   +:+          +:+ +:+    +:+ 
+#+#+  +#+    +:+  +#+ +#++:++#++     +#+    +#+    +:+     +#+       +#++:++#++      +#++:++#++: +#+    +:+ +#+   +#++:++#:    +#+      +#++:++#++ +#++:++#   +#+        +#++:++#+  +#++:++#   +#++:++#:         +#++:  ++#      +#++:++#+ +#++:++#++: +#+        +#+  +:+  +#+ +#++:++#++: +#+ +:+ +#+      +#+  +:+  +#+ +#++:++#:  +#++:++#++: +#++:++#+  +#++:++#+  +#+   +#++:++#     +#+ +#++:++#:  
+#+#+  +#+    +#+  +#+ +#+    +#+     +#+    +#+    +#+   +#+                +#+      +#+     +#+ +#+    +#+ +#+   +#+    +#+   +#+      +#+    +#+ +#+        +#+        +#+        +#+        +#+    +#+       +#+ +#+#+#       +#+       +#+     +#+ +#+        +#+       +#+ +#+     +#+ +#+  +#+#+#      +#+ +#+#+ +#+ +#+    +#+ +#+     +#+ +#+        +#+        +#+   +#+          +#+ +#+    +#+ 
+# #+# #+#    #+# #+#  #+#    #+#     #+#    #+#    #+#  #+#          #+#    #+#      #+#     #+# #+#    #+#  #+#  #+#    #+#  #+#       #+#    #+# #+#        #+#        #+#        #+#        #+#    #+#      #+#   #+#+        #+#       #+#     #+# #+#    #+# #+#       #+# #+#     #+# #+#   #+#+#       #+#+# #+#+#  #+#    #+# #+#     #+# #+#        #+#         #+#  #+#         #+#  #+#    #+# 
+#  ### ######## ###   ###    ### ########### ########  ##########     ########       ###     ###  ########    ### ###    ### ###        ###    ### ########## ########## ###        ########## ###    ###       ##########       ###       ###     ###  ########  ###       ### ###     ### ###    ####        ###   ###   ###    ### ###     ### ###        ###          ### ########## ###   ###    ### 
+# Eat Choco cake here!
 ore_dir=$HOME/.ore
 ore_ver="1-0"
 case $1 in 
-  -S) sudo pacman -S $2 2>/dev/null || echo -e '\e[34m:: \e[39mFetching package from AUR' && git clone "https://aur.archlinux.org/$2.git" $ore_dir/$2 && cd $ore_dir/$2 && makepkg -si 2>/dev/null && cd - && rm -rf $2 2>/dev/null && cd - 2>/dev/null || echo -e '\e[31m:: \e[39mPackage not found/PKGBUILD not found' ;;
+  -S) sudo pacman -S $2 10>/dev/null && [ $? -eq 0 ] || echo -e '\e[1m\e[34m:: \e[39m\e[1mFetching package from AUR\e[39m' && rm -rf $ore_dir/$2 && git clone "https://aur.archlinux.org/$2.git" $ore_dir/$2 && cd $ore_dir/$2 && makepkg -si 10>/dev/null && cd - && rm -rf $2 2>/dev/null && cd - 2>/dev/null && [ $?=0 ] || echo -e '\e[31m:: \e[39mError: Application quit with an non 0 code' ;;
+  -Syu) sudo pacman -Syu && cd $ore_dir && git pull * && cd - ;;
   -R) sudo pacman -R $2 2>/dev/null || echo -e '\e[31m:: \e[39mPackage not found' ;; 
-  -H) echo -e "\e[34m:: \e[39mOhio2's handy dandy AUR helper & pacman wrapper!" ;;
+  -H) echo -e "\e[34m:: \e[39mOhio2's handy dandy AUR helper & pacman wrapper!" && pacman -h ;;
   -V) echo -e "\e[34m:: \e[39m${ore_ver}" ;; 
-  -U) sudo pacman -U $2 2>/dev/null || echo -e '\e[31m:: \e[39mFile not found.' ;;  
-   $1) pacman $1 2>/dev/null || sudo pacman $1 2>/dev/null || echo -e '\e[31m:: \e[39mCommand not found' ;;
+  -U) sudo pacman -U $2 2>/dev/null || echo -e '\e[1m\e[31m:: \e[39m\e[1mFile not found.\e[39m' ;;  
+  $1) pacman $1 2>/dev/null || sudo pacman $1 2>/dev/null || echo -e '\e[31m:: \e[39mCommand not found' ;;
 esac
+
